# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-15 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='last_read',
            field=models.DateTimeField(),
        ),
    ]
