# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-15 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0002_auto_20190115_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingwa.Keyword')),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingwa.Url')),
            ],
        ),
    ]
