# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-05 02:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0004_auto_20190128_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utterence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterence', models.TextField()),
                ('count', models.IntegerField(default=0)),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lingwa.Language')),
            ],
        ),
    ]
