# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 02:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0007_auto_20190212_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicalclass',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lingwa.LexicalClass'),
        ),
    ]
