# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-12 03:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0008_auto_20190212_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lexicaldefinition',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_lexicaldefinition_translations_+', to='lingwa.LexicalDefinition'),
        ),
    ]
