# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-17 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0009_auto_20190212_0315'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterence',
            name='translations',
            field=models.ManyToManyField(blank=True, related_name='_utterence_translations_+', to='lingwa.Utterence'),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='lexical_definitions',
            field=models.ManyToManyField(related_name='keywords', through='lingwa.LexicalDefinition', to='lingwa.LexicalClass'),
        ),
    ]
