# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-27 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0010_auto_20190217_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='utterence',
            name='tokenised',
            field=models.BooleanField(default=False),
        ),
    ]
