# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-02-27 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0011_utterence_tokenised'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lingwa.Language'),
        ),
    ]
