# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0013_utterenceurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtterenceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingwa.Image')),
                ('utterence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingwa.Utterence')),
            ],
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-popular', 'name']},
        ),
    ]
