# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-01 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lingwa', '0014_auto_20190301_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingwa.Image')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lingwa.Keyword')),
            ],
        ),
    ]
